// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blocks.proto

package safex

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockHeader struct {
	Depth                uint64   `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	MajorVersion         uint32   `protobuf:"varint,3,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	MinorVersion         uint32   `protobuf:"varint,4,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
	PrevHash             string   `protobuf:"bytes,5,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_99dbce71772e5cd4, []int{0}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetDepth() uint64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *BlockHeader) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockHeader) GetMajorVersion() uint32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *BlockHeader) GetMinorVersion() uint32 {
	if m != nil {
		return m.MinorVersion
	}
	return 0
}

func (m *BlockHeader) GetPrevHash() string {
	if m != nil {
		return m.PrevHash
	}
	return ""
}

type Block struct {
	Header               *BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Txs                  []string     `protobuf:"bytes,2,rep,name=txs,proto3" json:"txs,omitempty"`
	MinerTx              string       `protobuf:"bytes,3,opt,name=miner_tx,json=minerTx,proto3" json:"miner_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_99dbce71772e5cd4, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTxs() []string {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *Block) GetMinerTx() string {
	if m != nil {
		return m.MinerTx
	}
	return ""
}

type Blocks struct {
	Block                []*Block `protobuf:"bytes,1,rep,name=block,proto3" json:"block,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Untrusted            bool     `protobuf:"varint,3,opt,name=untrusted,proto3" json:"untrusted,omitempty"`
	Error                string   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_99dbce71772e5cd4, []int{2}
}

func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (m *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(m, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Blocks) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Blocks) GetUntrusted() bool {
	if m != nil {
		return m.Untrusted
	}
	return false
}

func (m *Blocks) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "safex.BlockHeader")
	proto.RegisterType((*Block)(nil), "safex.Block")
	proto.RegisterType((*Blocks)(nil), "safex.Blocks")
}

func init() { proto.RegisterFile("blocks.proto", fileDescriptor_99dbce71772e5cd4) }

var fileDescriptor_99dbce71772e5cd4 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x4e, 0xb4, 0x30,
	0x14, 0xc5, 0xd3, 0xe1, 0xcf, 0x47, 0x2f, 0x4c, 0xf2, 0xe5, 0xc6, 0x18, 0x8c, 0x2e, 0x08, 0x6e,
	0x88, 0x0b, 0x16, 0xe3, 0x1b, 0xb8, 0x9a, 0x75, 0x63, 0xdc, 0x62, 0x47, 0x6a, 0x40, 0x1d, 0x4a,
	0xda, 0x32, 0xe1, 0x69, 0x7c, 0x56, 0xd3, 0x0b, 0x46, 0x76, 0xf7, 0xfc, 0x38, 0xe1, 0x9c, 0x7b,
	0x0b, 0xd9, 0xe9, 0x4b, 0xbf, 0x7d, 0xda, 0x7a, 0x34, 0xda, 0x69, 0x8c, 0xac, 0x7c, 0x57, 0x73,
	0xf9, 0xcd, 0x20, 0x7d, 0xf2, 0xfc, 0xa8, 0x64, 0xab, 0x0c, 0x5e, 0x41, 0xd4, 0xaa, 0xd1, 0x75,
	0x39, 0x2b, 0x58, 0x15, 0x8a, 0x45, 0x20, 0x42, 0xd8, 0x49, 0xdb, 0xe5, 0xbb, 0x82, 0x55, 0x5c,
	0xd0, 0x8c, 0xf7, 0xb0, 0x3f, 0xcb, 0x0f, 0x6d, 0x9a, 0x8b, 0x32, 0xb6, 0xd7, 0x43, 0x1e, 0x14,
	0xac, 0xda, 0x8b, 0x8c, 0xe0, 0xcb, 0xc2, 0xc8, 0xd4, 0x0f, 0x1b, 0x53, 0xb8, 0x9a, 0x3c, 0xfc,
	0x35, 0xdd, 0x02, 0x1f, 0x8d, 0xba, 0x34, 0x14, 0x11, 0x51, 0x44, 0xe2, 0xc1, 0x51, 0xda, 0xae,
	0x7c, 0x85, 0x88, 0xfa, 0xe1, 0x03, 0xc4, 0x1d, 0x75, 0xa4, 0x6a, 0xe9, 0x01, 0x6b, 0xda, 0xa0,
	0xde, 0xb4, 0x17, 0xab, 0x03, 0xff, 0x43, 0xe0, 0x66, 0x9b, 0xef, 0x8a, 0xa0, 0xe2, 0xc2, 0x8f,
	0x78, 0x03, 0xc9, 0xb9, 0x1f, 0x94, 0x69, 0xdc, 0x4c, 0x45, 0xb9, 0xf8, 0x47, 0xfa, 0x79, 0x2e,
	0x67, 0x88, 0xe9, 0x1f, 0x16, 0x4b, 0x88, 0xe8, 0x46, 0x39, 0x2b, 0x82, 0x2a, 0x3d, 0x64, 0xdb,
	0x04, 0xb1, 0x7c, 0xc2, 0x6b, 0x88, 0xad, 0x93, 0x6e, 0xb2, 0x74, 0x8c, 0x44, 0xac, 0x0a, 0xef,
	0x80, 0x4f, 0x83, 0x33, 0x93, 0x75, 0xaa, 0xa5, 0x84, 0x44, 0xfc, 0x01, 0x7f, 0x56, 0x65, 0x8c,
	0x36, 0xb4, 0x3f, 0x17, 0x8b, 0x38, 0xc5, 0xf4, 0x14, 0x8f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x7f, 0x71, 0xaa, 0xb4, 0x9a, 0x01, 0x00, 0x00,
}
