// Code generated by protoc-gen-go. DO NOT EDIT.
// source: get_outs.proto

package safex

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OutEntry struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Unlocked             bool     `protobuf:"varint,2,opt,name=unlocked,proto3" json:"unlocked,omitempty"`
	Height               uint64   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Txid                 []byte   `protobuf:"bytes,4,opt,name=txid,proto3" json:"txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutEntry) Reset()         { *m = OutEntry{} }
func (m *OutEntry) String() string { return proto.CompactTextString(m) }
func (*OutEntry) ProtoMessage()    {}
func (*OutEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_outs_62143c9662923c1b, []int{0}
}
func (m *OutEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutEntry.Unmarshal(m, b)
}
func (m *OutEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutEntry.Marshal(b, m, deterministic)
}
func (dst *OutEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutEntry.Merge(dst, src)
}
func (m *OutEntry) XXX_Size() int {
	return xxx_messageInfo_OutEntry.Size(m)
}
func (m *OutEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_OutEntry.DiscardUnknown(m)
}

var xxx_messageInfo_OutEntry proto.InternalMessageInfo

func (m *OutEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *OutEntry) GetUnlocked() bool {
	if m != nil {
		return m.Unlocked
	}
	return false
}

func (m *OutEntry) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *OutEntry) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

type Outs struct {
	Outs                 []*OutEntry `protobuf:"bytes,1,rep,name=outs,proto3" json:"outs,omitempty"`
	Status               string      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Outs) Reset()         { *m = Outs{} }
func (m *Outs) String() string { return proto.CompactTextString(m) }
func (*Outs) ProtoMessage()    {}
func (*Outs) Descriptor() ([]byte, []int) {
	return fileDescriptor_get_outs_62143c9662923c1b, []int{1}
}
func (m *Outs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outs.Unmarshal(m, b)
}
func (m *Outs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outs.Marshal(b, m, deterministic)
}
func (dst *Outs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outs.Merge(dst, src)
}
func (m *Outs) XXX_Size() int {
	return xxx_messageInfo_Outs.Size(m)
}
func (m *Outs) XXX_DiscardUnknown() {
	xxx_messageInfo_Outs.DiscardUnknown(m)
}

var xxx_messageInfo_Outs proto.InternalMessageInfo

func (m *Outs) GetOuts() []*OutEntry {
	if m != nil {
		return m.Outs
	}
	return nil
}

func (m *Outs) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*OutEntry)(nil), "safex.Out_entry")
	proto.RegisterType((*Outs)(nil), "safex.Outs")
}

func init() { proto.RegisterFile("get_outs.proto", fileDescriptor_get_outs_62143c9662923c1b) }

var fileDescriptor_get_outs_62143c9662923c1b = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x41, 0xca, 0x83, 0x30,
	0x10, 0x46, 0xc9, 0x6f, 0x7e, 0xd1, 0x69, 0x29, 0x92, 0x45, 0x09, 0x5d, 0x05, 0xe9, 0x22, 0x2b,
	0x17, 0xed, 0x15, 0xba, 0x17, 0x72, 0x01, 0xb1, 0x75, 0xaa, 0x62, 0x31, 0xc5, 0x4c, 0x40, 0x6f,
	0x5f, 0x0c, 0xe2, 0xee, 0x7b, 0x0c, 0xbc, 0x79, 0x70, 0x6a, 0x91, 0x2a, 0xeb, 0xc9, 0x15, 0xdf,
	0xc9, 0x92, 0x15, 0xff, 0xae, 0x7e, 0xe3, 0x9c, 0x23, 0xa4, 0xa5, 0xa7, 0x0a, 0x47, 0x9a, 0x16,
	0x91, 0x41, 0x34, 0xe0, 0x22, 0x99, 0x62, 0xfa, 0x68, 0xd6, 0x29, 0x2e, 0x90, 0xf8, 0xf1, 0x63,
	0x5f, 0x03, 0x36, 0xf2, 0x4f, 0x31, 0x9d, 0x98, 0x9d, 0xc5, 0x19, 0xe2, 0x0e, 0xfb, 0xb6, 0x23,
	0x19, 0x29, 0xa6, 0xb9, 0xd9, 0x48, 0x08, 0xe0, 0x34, 0xf7, 0x8d, 0xe4, 0x41, 0x13, 0x76, 0xfe,
	0x00, 0x5e, 0x7a, 0x72, 0xe2, 0x0a, 0x7c, 0x6d, 0x90, 0x4c, 0x45, 0xfa, 0x70, 0xcb, 0x8a, 0x10,
	0x51, 0xec, 0x05, 0x26, 0x5c, 0x57, 0xb3, 0xa3, 0x9a, 0xbc, 0x0b, 0x3f, 0x53, 0xb3, 0xd1, 0x33,
	0x0e, 0xe9, 0xf7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0xf1, 0x13, 0xf8, 0xcc, 0x00, 0x00,
	0x00,
}
