// Code generated by protoc-gen-go. DO NOT EDIT.
// source: output_histogram.proto

package safex

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Histogram struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	OutType              uint64   `protobuf:"varint,2,opt,name=out_type,json=outType,proto3" json:"out_type,omitempty"`
	RecentInstances      uint64   `protobuf:"varint,3,opt,name=recent_instances,json=recentInstances,proto3" json:"recent_instances,omitempty"`
	TotalInstances       uint64   `protobuf:"varint,4,opt,name=total_instances,json=totalInstances,proto3" json:"total_instances,omitempty"`
	UnlockedInstances    uint64   `protobuf:"varint,5,opt,name=unlocked_instances,json=unlockedInstances,proto3" json:"unlocked_instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Histogram) Reset()         { *m = Histogram{} }
func (m *Histogram) String() string { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()    {}
func (*Histogram) Descriptor() ([]byte, []int) {
	return fileDescriptor_output_histogram_927cbf93d7a0fad0, []int{0}
}
func (m *Histogram) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histogram.Unmarshal(m, b)
}
func (m *Histogram) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histogram.Marshal(b, m, deterministic)
}
func (dst *Histogram) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histogram.Merge(dst, src)
}
func (m *Histogram) XXX_Size() int {
	return xxx_messageInfo_Histogram.Size(m)
}
func (m *Histogram) XXX_DiscardUnknown() {
	xxx_messageInfo_Histogram.DiscardUnknown(m)
}

var xxx_messageInfo_Histogram proto.InternalMessageInfo

func (m *Histogram) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Histogram) GetOutType() uint64 {
	if m != nil {
		return m.OutType
	}
	return 0
}

func (m *Histogram) GetRecentInstances() uint64 {
	if m != nil {
		return m.RecentInstances
	}
	return 0
}

func (m *Histogram) GetTotalInstances() uint64 {
	if m != nil {
		return m.TotalInstances
	}
	return 0
}

func (m *Histogram) GetUnlockedInstances() uint64 {
	if m != nil {
		return m.UnlockedInstances
	}
	return 0
}

type Histograms struct {
	Histograms           []*Histogram `protobuf:"bytes,1,rep,name=histograms,proto3" json:"histograms,omitempty"`
	Status               string       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Histograms) Reset()         { *m = Histograms{} }
func (m *Histograms) String() string { return proto.CompactTextString(m) }
func (*Histograms) ProtoMessage()    {}
func (*Histograms) Descriptor() ([]byte, []int) {
	return fileDescriptor_output_histogram_927cbf93d7a0fad0, []int{1}
}
func (m *Histograms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Histograms.Unmarshal(m, b)
}
func (m *Histograms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Histograms.Marshal(b, m, deterministic)
}
func (dst *Histograms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Histograms.Merge(dst, src)
}
func (m *Histograms) XXX_Size() int {
	return xxx_messageInfo_Histograms.Size(m)
}
func (m *Histograms) XXX_DiscardUnknown() {
	xxx_messageInfo_Histograms.DiscardUnknown(m)
}

var xxx_messageInfo_Histograms proto.InternalMessageInfo

func (m *Histograms) GetHistograms() []*Histogram {
	if m != nil {
		return m.Histograms
	}
	return nil
}

func (m *Histograms) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Histogram)(nil), "safex.Histogram")
	proto.RegisterType((*Histograms)(nil), "safex.Histograms")
}

func init() {
	proto.RegisterFile("output_histogram.proto", fileDescriptor_output_histogram_927cbf93d7a0fad0)
}

var fileDescriptor_output_histogram_927cbf93d7a0fad0 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x05, 0x60, 0x99, 0xfd, 0x81, 0x1d, 0x24, 0x76, 0x71, 0xb1, 0x32, 0xdd, 0x2a, 0x0d, 0xa1,
	0x20, 0x42, 0x70, 0x09, 0x68, 0x23, 0x44, 0x1b, 0x99, 0x60, 0x20, 0x22, 0xf1, 0x58, 0x99, 0xb1,
	0x44, 0x8e, 0xc7, 0xcd, 0x10, 0x43, 0xe2, 0x4d, 0x39, 0xef, 0x7d, 0xcd, 0x1b, 0xd8, 0x63, 0xe4,
	0x10, 0xb9, 0xfa, 0x6c, 0x88, 0xf1, 0xa3, 0xb7, 0x5d, 0x11, 0x7a, 0x64, 0xd4, 0x2b, 0xb2, 0xef,
	0xee, 0x3b, 0xfb, 0x51, 0xb0, 0x79, 0x9c, 0x2a, 0xbd, 0x87, 0xb5, 0xed, 0x30, 0x7a, 0x36, 0xea,
	0xa0, 0xf2, 0x65, 0x39, 0x5e, 0xfa, 0x0a, 0xce, 0x30, 0x72, 0xc5, 0x43, 0x70, 0xe6, 0x44, 0x9a,
	0x53, 0x8c, 0xfc, 0x3c, 0x04, 0xa7, 0x6f, 0x60, 0xd7, 0xbb, 0xda, 0x79, 0xae, 0x1a, 0x4f, 0x6c,
	0x7d, 0xed, 0xc8, 0x2c, 0x84, 0x6c, 0xff, 0xf3, 0xa7, 0x29, 0xd6, 0xd7, 0xb0, 0x65, 0x64, 0xdb,
	0xce, 0xe4, 0x52, 0xe4, 0x85, 0xc4, 0x47, 0x78, 0x0b, 0x3a, 0xfa, 0x16, 0xeb, 0x2f, 0xf7, 0x36,
	0xb3, 0x2b, 0xb1, 0x97, 0x53, 0x93, 0x78, 0xf6, 0x02, 0x90, 0x26, 0x90, 0xbe, 0x03, 0x48, 0x5b,
	0xc9, 0xa8, 0xc3, 0x22, 0x3f, 0xbf, 0xdf, 0x15, 0xb2, 0xb6, 0x48, 0xac, 0x9c, 0x99, 0xbf, 0xd5,
	0xc4, 0x96, 0x23, 0xc9, 0xb6, 0x4d, 0x39, 0x5e, 0xaf, 0x6b, 0xf9, 0xd4, 0xc3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5b, 0x3b, 0x85, 0x42, 0x43, 0x01, 0x00, 0x00,
}
