// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactions.proto

package safex

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TxinGen struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxinGen) Reset()         { *m = TxinGen{} }
func (m *TxinGen) String() string { return proto.CompactTextString(m) }
func (*TxinGen) ProtoMessage()    {}
func (*TxinGen) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{0}
}

func (m *TxinGen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxinGen.Unmarshal(m, b)
}
func (m *TxinGen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxinGen.Marshal(b, m, deterministic)
}
func (m *TxinGen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxinGen.Merge(m, src)
}
func (m *TxinGen) XXX_Size() int {
	return xxx_messageInfo_TxinGen.Size(m)
}
func (m *TxinGen) XXX_DiscardUnknown() {
	xxx_messageInfo_TxinGen.DiscardUnknown(m)
}

var xxx_messageInfo_TxinGen proto.InternalMessageInfo

func (m *TxinGen) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type TxinToKey struct {
	Amount               uint64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	KImage               []byte   `protobuf:"bytes,2,opt,name=k_image,json=kImage,proto3" json:"k_image,omitempty"`
	KeyOffsets           []uint64 `protobuf:"varint,3,rep,packed,name=key_offsets,json=keyOffsets,proto3" json:"key_offsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxinToKey) Reset()         { *m = TxinToKey{} }
func (m *TxinToKey) String() string { return proto.CompactTextString(m) }
func (*TxinToKey) ProtoMessage()    {}
func (*TxinToKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{1}
}

func (m *TxinToKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxinToKey.Unmarshal(m, b)
}
func (m *TxinToKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxinToKey.Marshal(b, m, deterministic)
}
func (m *TxinToKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxinToKey.Merge(m, src)
}
func (m *TxinToKey) XXX_Size() int {
	return xxx_messageInfo_TxinToKey.Size(m)
}
func (m *TxinToKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TxinToKey.DiscardUnknown(m)
}

var xxx_messageInfo_TxinToKey proto.InternalMessageInfo

func (m *TxinToKey) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TxinToKey) GetKImage() []byte {
	if m != nil {
		return m.KImage
	}
	return nil
}

func (m *TxinToKey) GetKeyOffsets() []uint64 {
	if m != nil {
		return m.KeyOffsets
	}
	return nil
}

type TxinTokenToKey struct {
	TokenAmount          uint64   `protobuf:"varint,1,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	KImage               []byte   `protobuf:"bytes,2,opt,name=k_image,json=kImage,proto3" json:"k_image,omitempty"`
	KeyOffsets           []uint64 `protobuf:"varint,3,rep,packed,name=key_offsets,json=keyOffsets,proto3" json:"key_offsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxinTokenToKey) Reset()         { *m = TxinTokenToKey{} }
func (m *TxinTokenToKey) String() string { return proto.CompactTextString(m) }
func (*TxinTokenToKey) ProtoMessage()    {}
func (*TxinTokenToKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{2}
}

func (m *TxinTokenToKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxinTokenToKey.Unmarshal(m, b)
}
func (m *TxinTokenToKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxinTokenToKey.Marshal(b, m, deterministic)
}
func (m *TxinTokenToKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxinTokenToKey.Merge(m, src)
}
func (m *TxinTokenToKey) XXX_Size() int {
	return xxx_messageInfo_TxinTokenToKey.Size(m)
}
func (m *TxinTokenToKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TxinTokenToKey.DiscardUnknown(m)
}

var xxx_messageInfo_TxinTokenToKey proto.InternalMessageInfo

func (m *TxinTokenToKey) GetTokenAmount() uint64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *TxinTokenToKey) GetKImage() []byte {
	if m != nil {
		return m.KImage
	}
	return nil
}

func (m *TxinTokenToKey) GetKeyOffsets() []uint64 {
	if m != nil {
		return m.KeyOffsets
	}
	return nil
}

type TxinTokenMigration struct {
	TokenAmount            uint64   `protobuf:"varint,1,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	BitcoinBurnTransaction string   `protobuf:"bytes,2,opt,name=bitcoin_burn_transaction,json=bitcoinBurnTransaction,proto3" json:"bitcoin_burn_transaction,omitempty"`
	KImage                 []byte   `protobuf:"bytes,3,opt,name=k_image,json=kImage,proto3" json:"k_image,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TxinTokenMigration) Reset()         { *m = TxinTokenMigration{} }
func (m *TxinTokenMigration) String() string { return proto.CompactTextString(m) }
func (*TxinTokenMigration) ProtoMessage()    {}
func (*TxinTokenMigration) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{3}
}

func (m *TxinTokenMigration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxinTokenMigration.Unmarshal(m, b)
}
func (m *TxinTokenMigration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxinTokenMigration.Marshal(b, m, deterministic)
}
func (m *TxinTokenMigration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxinTokenMigration.Merge(m, src)
}
func (m *TxinTokenMigration) XXX_Size() int {
	return xxx_messageInfo_TxinTokenMigration.Size(m)
}
func (m *TxinTokenMigration) XXX_DiscardUnknown() {
	xxx_messageInfo_TxinTokenMigration.DiscardUnknown(m)
}

var xxx_messageInfo_TxinTokenMigration proto.InternalMessageInfo

func (m *TxinTokenMigration) GetTokenAmount() uint64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *TxinTokenMigration) GetBitcoinBurnTransaction() string {
	if m != nil {
		return m.BitcoinBurnTransaction
	}
	return ""
}

func (m *TxinTokenMigration) GetKImage() []byte {
	if m != nil {
		return m.KImage
	}
	return nil
}

// Variants are implemented with optional fields
type TxinV struct {
	TxinGen              *TxinGen            `protobuf:"bytes,1,opt,name=txin_gen,json=txinGen,proto3" json:"txin_gen,omitempty"`
	TxinToKey            *TxinToKey          `protobuf:"bytes,2,opt,name=txin_to_key,json=txinToKey,proto3" json:"txin_to_key,omitempty"`
	TxinTokenToKey       *TxinTokenToKey     `protobuf:"bytes,3,opt,name=txin_token_to_key,json=txinTokenToKey,proto3" json:"txin_token_to_key,omitempty"`
	TxinTokenMigration   *TxinTokenMigration `protobuf:"bytes,4,opt,name=txin_token_migration,json=txinTokenMigration,proto3" json:"txin_token_migration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TxinV) Reset()         { *m = TxinV{} }
func (m *TxinV) String() string { return proto.CompactTextString(m) }
func (*TxinV) ProtoMessage()    {}
func (*TxinV) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{4}
}

func (m *TxinV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxinV.Unmarshal(m, b)
}
func (m *TxinV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxinV.Marshal(b, m, deterministic)
}
func (m *TxinV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxinV.Merge(m, src)
}
func (m *TxinV) XXX_Size() int {
	return xxx_messageInfo_TxinV.Size(m)
}
func (m *TxinV) XXX_DiscardUnknown() {
	xxx_messageInfo_TxinV.DiscardUnknown(m)
}

var xxx_messageInfo_TxinV proto.InternalMessageInfo

func (m *TxinV) GetTxinGen() *TxinGen {
	if m != nil {
		return m.TxinGen
	}
	return nil
}

func (m *TxinV) GetTxinToKey() *TxinToKey {
	if m != nil {
		return m.TxinToKey
	}
	return nil
}

func (m *TxinV) GetTxinTokenToKey() *TxinTokenToKey {
	if m != nil {
		return m.TxinTokenToKey
	}
	return nil
}

func (m *TxinV) GetTxinTokenMigration() *TxinTokenMigration {
	if m != nil {
		return m.TxinTokenMigration
	}
	return nil
}

type TxoutToKey struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxoutToKey) Reset()         { *m = TxoutToKey{} }
func (m *TxoutToKey) String() string { return proto.CompactTextString(m) }
func (*TxoutToKey) ProtoMessage()    {}
func (*TxoutToKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{5}
}

func (m *TxoutToKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxoutToKey.Unmarshal(m, b)
}
func (m *TxoutToKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxoutToKey.Marshal(b, m, deterministic)
}
func (m *TxoutToKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxoutToKey.Merge(m, src)
}
func (m *TxoutToKey) XXX_Size() int {
	return xxx_messageInfo_TxoutToKey.Size(m)
}
func (m *TxoutToKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TxoutToKey.DiscardUnknown(m)
}

var xxx_messageInfo_TxoutToKey proto.InternalMessageInfo

func (m *TxoutToKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type TxoutTokenToKey struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxoutTokenToKey) Reset()         { *m = TxoutTokenToKey{} }
func (m *TxoutTokenToKey) String() string { return proto.CompactTextString(m) }
func (*TxoutTokenToKey) ProtoMessage()    {}
func (*TxoutTokenToKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{6}
}

func (m *TxoutTokenToKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxoutTokenToKey.Unmarshal(m, b)
}
func (m *TxoutTokenToKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxoutTokenToKey.Marshal(b, m, deterministic)
}
func (m *TxoutTokenToKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxoutTokenToKey.Merge(m, src)
}
func (m *TxoutTokenToKey) XXX_Size() int {
	return xxx_messageInfo_TxoutTokenToKey.Size(m)
}
func (m *TxoutTokenToKey) XXX_DiscardUnknown() {
	xxx_messageInfo_TxoutTokenToKey.DiscardUnknown(m)
}

var xxx_messageInfo_TxoutTokenToKey proto.InternalMessageInfo

func (m *TxoutTokenToKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type TxoutTargetV struct {
	TxoutToKey           *TxoutToKey      `protobuf:"bytes,1,opt,name=txout_to_key,json=txoutToKey,proto3" json:"txout_to_key,omitempty"`
	TxoutTokenToKey      *TxoutTokenToKey `protobuf:"bytes,2,opt,name=txout_token_to_key,json=txoutTokenToKey,proto3" json:"txout_token_to_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TxoutTargetV) Reset()         { *m = TxoutTargetV{} }
func (m *TxoutTargetV) String() string { return proto.CompactTextString(m) }
func (*TxoutTargetV) ProtoMessage()    {}
func (*TxoutTargetV) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{7}
}

func (m *TxoutTargetV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxoutTargetV.Unmarshal(m, b)
}
func (m *TxoutTargetV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxoutTargetV.Marshal(b, m, deterministic)
}
func (m *TxoutTargetV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxoutTargetV.Merge(m, src)
}
func (m *TxoutTargetV) XXX_Size() int {
	return xxx_messageInfo_TxoutTargetV.Size(m)
}
func (m *TxoutTargetV) XXX_DiscardUnknown() {
	xxx_messageInfo_TxoutTargetV.DiscardUnknown(m)
}

var xxx_messageInfo_TxoutTargetV proto.InternalMessageInfo

func (m *TxoutTargetV) GetTxoutToKey() *TxoutToKey {
	if m != nil {
		return m.TxoutToKey
	}
	return nil
}

func (m *TxoutTargetV) GetTxoutTokenToKey() *TxoutTokenToKey {
	if m != nil {
		return m.TxoutTokenToKey
	}
	return nil
}

type Txout struct {
	Amount               uint64        `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	TokenAmount          uint64        `protobuf:"varint,2,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	Target               *TxoutTargetV `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Txout) Reset()         { *m = Txout{} }
func (m *Txout) String() string { return proto.CompactTextString(m) }
func (*Txout) ProtoMessage()    {}
func (*Txout) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{8}
}

func (m *Txout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Txout.Unmarshal(m, b)
}
func (m *Txout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Txout.Marshal(b, m, deterministic)
}
func (m *Txout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Txout.Merge(m, src)
}
func (m *Txout) XXX_Size() int {
	return xxx_messageInfo_Txout.Size(m)
}
func (m *Txout) XXX_DiscardUnknown() {
	xxx_messageInfo_Txout.DiscardUnknown(m)
}

var xxx_messageInfo_Txout proto.InternalMessageInfo

func (m *Txout) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Txout) GetTokenAmount() uint64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *Txout) GetTarget() *TxoutTargetV {
	if m != nil {
		return m.Target
	}
	return nil
}

type SigData struct {
	R                    []byte   `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	C                    []byte   `protobuf:"bytes,2,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigData) Reset()         { *m = SigData{} }
func (m *SigData) String() string { return proto.CompactTextString(m) }
func (*SigData) ProtoMessage()    {}
func (*SigData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{9}
}

func (m *SigData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigData.Unmarshal(m, b)
}
func (m *SigData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigData.Marshal(b, m, deterministic)
}
func (m *SigData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigData.Merge(m, src)
}
func (m *SigData) XXX_Size() int {
	return xxx_messageInfo_SigData.Size(m)
}
func (m *SigData) XXX_DiscardUnknown() {
	xxx_messageInfo_SigData.DiscardUnknown(m)
}

var xxx_messageInfo_SigData proto.InternalMessageInfo

func (m *SigData) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *SigData) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

type Signature struct {
	Signature            []*SigData `protobuf:"bytes,1,rep,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{10}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignature() []*SigData {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Transaction struct {
	Version              uint64       `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	UnlockTime           uint64       `protobuf:"varint,2,opt,name=unlock_time,json=unlockTime,proto3" json:"unlock_time,omitempty"`
	Extra                []byte       `protobuf:"bytes,3,opt,name=extra,proto3" json:"extra,omitempty"`
	Vin                  []*TxinV     `protobuf:"bytes,4,rep,name=vin,proto3" json:"vin,omitempty"`
	Vout                 []*Txout     `protobuf:"bytes,5,rep,name=vout,proto3" json:"vout,omitempty"`
	Signatures           []*Signature `protobuf:"bytes,6,rep,name=signatures,proto3" json:"signatures,omitempty"`
	BlockHeight          uint64       `protobuf:"varint,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTimestamp       uint64       `protobuf:"varint,8,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	DoubleSpendSeen      bool         `protobuf:"varint,9,opt,name=double_spend_seen,json=doubleSpendSeen,proto3" json:"double_spend_seen,omitempty"`
	InPool               bool         `protobuf:"varint,10,opt,name=in_pool,json=inPool,proto3" json:"in_pool,omitempty"`
	OutputIndices        []uint64     `protobuf:"varint,11,rep,packed,name=output_indices,json=outputIndices,proto3" json:"output_indices,omitempty"`
	TxHash               string       `protobuf:"bytes,12,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{11}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Transaction) GetUnlockTime() uint64 {
	if m != nil {
		return m.UnlockTime
	}
	return 0
}

func (m *Transaction) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

func (m *Transaction) GetVin() []*TxinV {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *Transaction) GetVout() []*Txout {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *Transaction) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Transaction) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Transaction) GetBlockTimestamp() uint64 {
	if m != nil {
		return m.BlockTimestamp
	}
	return 0
}

func (m *Transaction) GetDoubleSpendSeen() bool {
	if m != nil {
		return m.DoubleSpendSeen
	}
	return false
}

func (m *Transaction) GetInPool() bool {
	if m != nil {
		return m.InPool
	}
	return false
}

func (m *Transaction) GetOutputIndices() []uint64 {
	if m != nil {
		return m.OutputIndices
	}
	return nil
}

func (m *Transaction) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type Transactions struct {
	Tx                   []*Transaction `protobuf:"bytes,1,rep,name=tx,proto3" json:"tx,omitempty"`
	MissedTxs            []string       `protobuf:"bytes,2,rep,name=missed_txs,json=missedTxs,proto3" json:"missed_txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b72849cf10e9c77, []int{12}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTx() []*Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *Transactions) GetMissedTxs() []string {
	if m != nil {
		return m.MissedTxs
	}
	return nil
}

func init() {
	proto.RegisterType((*TxinGen)(nil), "safex.txin_gen")
	proto.RegisterType((*TxinToKey)(nil), "safex.txin_to_key")
	proto.RegisterType((*TxinTokenToKey)(nil), "safex.txin_token_to_key")
	proto.RegisterType((*TxinTokenMigration)(nil), "safex.txin_token_migration")
	proto.RegisterType((*TxinV)(nil), "safex.txin_v")
	proto.RegisterType((*TxoutToKey)(nil), "safex.txout_to_key")
	proto.RegisterType((*TxoutTokenToKey)(nil), "safex.txout_token_to_key")
	proto.RegisterType((*TxoutTargetV)(nil), "safex.txout_target_v")
	proto.RegisterType((*Txout)(nil), "safex.txout")
	proto.RegisterType((*SigData)(nil), "safex.SigData")
	proto.RegisterType((*Signature)(nil), "safex.Signature")
	proto.RegisterType((*Transaction)(nil), "safex.Transaction")
	proto.RegisterType((*Transactions)(nil), "safex.Transactions")
}

func init() { proto.RegisterFile("transactions.proto", fileDescriptor_0b72849cf10e9c77) }

var fileDescriptor_0b72849cf10e9c77 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x86, 0x2c, 0x5b, 0x8e, 0x8f, 0x1c, 0x3b, 0xe1, 0xb2, 0x8c, 0xc3, 0x30, 0x44, 0x13, 0x90,
	0xcd, 0x08, 0xb6, 0x60, 0xf0, 0x30, 0x60, 0xbb, 0xdc, 0x5a, 0xb4, 0x09, 0x8a, 0xa0, 0x2d, 0xed,
	0x7b, 0x41, 0xb6, 0x19, 0x9b, 0x90, 0x4d, 0xba, 0x22, 0x65, 0xc8, 0xef, 0x50, 0xa0, 0x2f, 0xd1,
	0xc7, 0xec, 0x45, 0xc1, 0x1f, 0xd9, 0x72, 0x92, 0x02, 0x05, 0x7a, 0xa7, 0xf3, 0x9d, 0x8f, 0xe7,
	0xe7, 0x3b, 0x87, 0x14, 0x20, 0x95, 0xa7, 0x5c, 0xa6, 0x53, 0xc5, 0x04, 0x97, 0xd7, 0xeb, 0x5c,
	0x28, 0x81, 0x5a, 0x32, 0xbd, 0xa7, 0x65, 0x1c, 0xc3, 0x91, 0x2a, 0x19, 0x4f, 0xe6, 0x94, 0xa3,
	0x73, 0x08, 0x16, 0x94, 0xcd, 0x17, 0x0a, 0x7b, 0x91, 0x37, 0x68, 0x12, 0x67, 0xc5, 0x09, 0x84,
	0x86, 0xa3, 0x44, 0x92, 0xd1, 0xad, 0xa6, 0xa5, 0x2b, 0x51, 0xf0, 0x1d, 0xcd, 0x5a, 0xe8, 0x07,
	0x68, 0x67, 0x09, 0x5b, 0xa5, 0x73, 0x8a, 0x1b, 0x91, 0x37, 0xe8, 0x92, 0x20, 0xbb, 0xd5, 0x16,
	0xba, 0x80, 0x30, 0xa3, 0xdb, 0x44, 0xdc, 0xdf, 0x4b, 0xaa, 0x24, 0xf6, 0x23, 0x7f, 0xd0, 0x24,
	0x90, 0xd1, 0xed, 0x6b, 0x8b, 0xc4, 0x6b, 0x38, 0x75, 0x09, 0x32, 0xba, 0x4b, 0xf3, 0x0b, 0x74,
	0xad, 0x7d, 0x90, 0x2c, 0x34, 0xd8, 0x7f, 0xdf, 0x9a, 0xf1, 0xbd, 0x07, 0x67, 0xb5, 0x94, 0x2b,
	0x36, 0xcf, 0x53, 0xad, 0xce, 0xd7, 0x64, 0xfd, 0x07, 0xf0, 0x84, 0xa9, 0xa9, 0x60, 0x3c, 0x99,
	0x14, 0x39, 0x4f, 0x6a, 0xe2, 0x9a, 0x32, 0x3a, 0xe4, 0xdc, 0xf9, 0xff, 0x2f, 0x72, 0x3e, 0xde,
	0x7b, 0xeb, 0xf5, 0xfa, 0xf5, 0x7a, 0xe3, 0x4f, 0x1e, 0x04, 0xa6, 0x9c, 0x0d, 0xba, 0xda, 0x0f,
	0xc4, 0x24, 0x0f, 0x87, 0xfd, 0x6b, 0x33, 0xaa, 0xeb, 0x0a, 0x26, 0x6d, 0xfd, 0xf5, 0x92, 0x72,
	0x34, 0x3c, 0x18, 0x8c, 0x49, 0x1e, 0x0e, 0x51, 0x9d, 0x6e, 0x3d, 0xa4, 0xa3, 0x8d, 0xb1, 0x78,
	0x45, 0xb7, 0xe8, 0xd9, 0x13, 0x5a, 0x9b, 0x6a, 0xc2, 0x21, 0x3e, 0x3c, 0xb9, 0xf7, 0x93, 0x9e,
	0x3d, 0x9f, 0x51, 0x17, 0xe4, 0xee, 0x69, 0xf5, 0x70, 0xd3, 0xc4, 0xf9, 0xe9, 0x71, 0x9c, 0x1d,
	0x85, 0xa0, 0x5d, 0xa8, 0xbb, 0x0a, 0x8b, 0x23, 0xe8, 0xaa, 0x52, 0x14, 0xaa, 0x1a, 0xfd, 0x09,
	0xf8, 0xba, 0x2a, 0xcf, 0x68, 0xa4, 0x3f, 0xe3, 0x5f, 0x01, 0x55, 0x8c, 0xda, 0x8a, 0x3c, 0xe6,
	0x7d, 0xf0, 0xa0, 0xe7, 0x88, 0x69, 0x3e, 0xa7, 0x2a, 0xd9, 0xa0, 0xbf, 0x0f, 0x83, 0x3b, 0x51,
	0xbf, 0xdb, 0xd5, 0xb8, 0x77, 0x11, 0x30, 0x96, 0x6d, 0xf1, 0xc5, 0x53, 0x19, 0x9d, 0xc4, 0x3f,
	0x3e, 0x38, 0x5c, 0x53, 0xaa, 0xef, 0x42, 0x54, 0x52, 0xc5, 0xef, 0xa0, 0x65, 0xa0, 0x2f, 0x5e,
	0x9b, 0x87, 0x1b, 0xd7, 0x78, 0xbc, 0x71, 0x7f, 0x40, 0x60, 0xdb, 0x71, 0x83, 0xfa, 0xfe, 0x30,
	0xbf, 0xeb, 0x94, 0x38, 0x52, 0x7c, 0x09, 0xed, 0x11, 0x9b, 0x3f, 0x4f, 0x55, 0x8a, 0xba, 0xe0,
	0xe5, 0x4e, 0x1f, 0x2f, 0xd7, 0xd6, 0xd4, 0xdd, 0x14, 0x6f, 0x1a, 0xff, 0x0b, 0x9d, 0x11, 0x9b,
	0xf3, 0x54, 0x15, 0x39, 0x45, 0xbf, 0x43, 0x47, 0x56, 0x06, 0xf6, 0x22, 0x7f, 0x10, 0x0e, 0x7b,
	0x2e, 0x8b, 0x8b, 0x45, 0xf6, 0x84, 0xf8, 0xa3, 0x0f, 0x61, 0x7d, 0xb1, 0x31, 0xb4, 0x37, 0x34,
	0x97, 0x7a, 0x05, 0x6c, 0x73, 0x95, 0xa9, 0x6f, 0x62, 0xc1, 0x97, 0x62, 0x9a, 0x25, 0x8a, 0xad,
	0xa8, 0x6b, 0x0e, 0x2c, 0x34, 0x66, 0x2b, 0x8a, 0xce, 0xa0, 0x45, 0x4b, 0x95, 0xa7, 0xee, 0x46,
	0x58, 0x03, 0x5d, 0x80, 0xbf, 0x61, 0x7a, 0x9f, 0x74, 0x21, 0xc7, 0xf5, 0x7d, 0xda, 0x10, 0xed,
	0x41, 0x11, 0x34, 0x37, 0xa2, 0x50, 0xb8, 0x65, 0x18, 0xdd, 0xba, 0x20, 0xc4, 0x78, 0xd0, 0x9f,
	0x00, 0xbb, 0x82, 0x25, 0x0e, 0x0c, 0xef, 0x64, 0xdf, 0x92, 0x75, 0x90, 0x1a, 0x47, 0x4f, 0x62,
	0x62, 0x4a, 0x75, 0xaf, 0x60, 0xdb, 0x4e, 0xc2, 0x60, 0x37, 0x06, 0x42, 0xbf, 0x41, 0x7f, 0xb2,
	0xeb, 0x46, 0xaa, 0x74, 0xb5, 0xc6, 0x47, 0x86, 0xd5, 0x9b, 0x54, 0x1d, 0x19, 0x14, 0x5d, 0xc1,
	0xe9, 0x4c, 0x14, 0x93, 0x25, 0x4d, 0xe4, 0x9a, 0xf2, 0x59, 0x22, 0x29, 0xe5, 0xb8, 0x13, 0x79,
	0x83, 0x23, 0xd2, 0xb7, 0x8e, 0x91, 0xc6, 0x47, 0x94, 0x9a, 0x67, 0x81, 0xf1, 0x64, 0x2d, 0xc4,
	0x12, 0x83, 0x61, 0x04, 0x8c, 0xbf, 0x11, 0x62, 0x89, 0x2e, 0xa1, 0x27, 0x0a, 0xb5, 0x2e, 0x54,
	0xc2, 0xf8, 0x8c, 0x4d, 0xa9, 0xc4, 0xa1, 0x79, 0xc9, 0x8e, 0x2d, 0x7a, 0x6b, 0x41, 0x7d, 0x5e,
	0x95, 0xc9, 0x22, 0x95, 0x0b, 0xdc, 0x35, 0xef, 0x4f, 0xa0, 0xca, 0x9b, 0x54, 0x2e, 0xe2, 0xb7,
	0xd0, 0xad, 0x4d, 0x49, 0xa2, 0x18, 0x1a, 0xaa, 0x74, 0xd3, 0xad, 0x9e, 0x89, 0x1a, 0x81, 0x34,
	0x54, 0x89, 0x7e, 0x06, 0x58, 0x31, 0x29, 0xe9, 0x2c, 0x51, 0xa5, 0xc4, 0x8d, 0xc8, 0x1f, 0x74,
	0x48, 0xc7, 0x22, 0xe3, 0x52, 0x4e, 0x02, 0xf3, 0xf7, 0xf8, 0xeb, 0x73, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa3, 0xf9, 0x6a, 0xf9, 0x53, 0x06, 0x00, 0x00,
}
